name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
    AZURE_WEBAPP_NAME: nojoom
    AZURE_WEBAPP_PACKAGE_PATH: "./publish"  
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'
    - run: npm ci
    - run: npm run build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH into VM and deploy
        uses: appleboy/ssh-action@master
        with:
          host: 172.210.59.191
          username: nojoomserver
          key: |
            -----BEGIN RSA PRIVATE KEY-----
            MIIG5gIBAAKCAYEAxvO280R+Z8tahil0jQ+w3ZDdXzb2aGVGqtIDoQOtr8WyiMvD
            uz7VeB4rJkQ2HAjSylBsttEItSQK8Wg9e1PEtYIXcZ0iHP+nWY+IGOqBs45EZBT5
            ew8LKLdV8hmgRsP3QtVYiyI6AUfc/5MzAJFCiJVRUa5i+BwAlcAuuVQRTzWSnrWa
            qOjMUkF/Bef3CmqG7K1o9509DBINFxAnu8n0osVnZiEgH0T89GGu8sTcbKa3Vfxn
            Buf576V4BIePLLucoQxtYDsuNZpom8O8afxH6enChqAHYatNyMkCH5NFCcocnzkv
            trDuOZA0h44Gqht0AqYn1WT2ftilLNMlYprWGygjFFqKYkDa9lAl2mDe2hiAKsJz
            bDnFnPRwwBM1BrXhpyMQr90uHhsWasEhh0V27YBDlgfXkDJExq9/7LpeWW8xGVSZ
            4GRypl2UmBjtWYtXV40q6b1SZgVvuEUgdj1wjgjc1U4siAkVjsIT+GWVUyrcN7tN
            6XANexRZU9c2kQJpAgMBAAECggGBAKb4f4Cm6Vd/CVgzjoectZkeLUvtuttes/JF
            E5qclbZBO1cne/u3/jwzRY92C9t3ZEE7QiIkSSSNPUnhbEgGw755kedeMvUXcoHt
            vhD7LyNcsPU1zTOEKp9fTphC/YqmiOvkVc1fSkMs5sLv7Qv63VX3yym8K3+DMNJ9
            Wjlb3rMViRn92/EKgABAy7RPO7vYL6iO2NuHcWah9651doNaOSAqgF7sSiM0KP+I
            w+UnZr8hJBjcHjNjmRWRT6qtgnHOeWg5FYrNxz5ut1WtD9f7NA31CdOb6xT0Es1Y
            DMKKwMV30E/OY+pdzCbCiIZNDVQbKLisdU+6X66q3/amkd0PBZU7hIX1gQRD7CbO
            sLEq93DgDtMM1fmEWJ4WPNUIhHzxdKEpJ+LXsCdTIFq0BLMHruogX/r8DjxyAy23
            46u8ys1yZpqRFuxArhXzVPqBYc9c9enQRvjW0xf4IXgAIwV+H/xDAnJowGHvGbBR
            sWhhSwHe1SVoafaHI7hYugHES8aOiQKBwQDWZ7p+Dx4mJYOI3iNCY+iy11BXyOCw
            U/ybK2McvNYyniHRd9YlEvOMGys1ww/01S5KkQ9rV9ve6xBUzSAhnN25z2dICv42
            NfN1n27YYRtBe52WeA7DugCDHzxGQoYccwyqk9rW+R9MQM4PFIgC0gLFmqItBzSg
            Ws6LKThllOfRYMNH7EMAuYjSujLbsR3T/QFN36p1unjNCOtPSttrxUhlc0kvYqpD
            BLBIDkOybjBQGs4mve9FI3qGibDSV4pIwB8CgcEA7YyEBhRCkZV3nEFF6TP8dmT4
            GH3GS+q2iNsrjUeX5oAmhPeE0FJ7mefV1DN77fjKr6JFoEHssyXlfN6mwzCBJK0l
            gFxJZGJUhf4LhctChY9l6UpXhZvAXFlk8MsZqTr6NZq9L+ucqWs2TMdKaB9nv4fT
            Ye17kV2vvkUyCSZ035cb8WmZMTuWpAk0tdT0TA/CUEijRaLIstJhDghuz501SDX2
            l/OFH8s7eSihYB7nXcb5/HwOMPCe/ArbUe35ecx3AoHBAIhZoyIz3wqHZOUP0ACS
            pRPHFlMdbrb0Unsj1n4aIWZDZmJeAZPGP5hkVtBz4pvjTvMg2Vt8nllfyB0F7l8x
            8VgPbDFGvHAhU1kEMWvuJXU5dfiRFWKn0VeR77UG7V7+U5nPOabo+1x1AhZZCj4w
            7I5aTrSwFmm8FgouBq2jSuG+1bHRsLKvSzIoM9u/AaclCUVK7o68LcLG306n3m7l
            IatS68H0zy6btre8SpUYuiTXRy8gLyAa9frFaev6u/iUJQKBwQDsJ0UYxgtnr6+5
            JyrZK1VQXhBGSMNZtXzBkSE60nGwNLYWefsPHvDBkDiDPKt3aF4XPLr7Fo65inMa
            MD6YzR+V1ovxj81mflqI2oWZ/Pekz2oBAmb/7FbPeA9hUoewNXGI2Mw7V3/m7S6O
            JZFS8eWyAtWiBPVTDlAoV6HmdtS5cv/Uf6ZLy3F2obBFE+/JreD+7zdhgvMC0yKp
            ULjYrPDLWNpNNUqi0OfPCxVi+VYJZEYhOzLgdFWZOzHNwUbCTwECgcEAw2Qxbj4n
            TdL27NvLi7kubjtWiR+4394rcaYDf8eENr+N4K3/1BeAyobsMNDgzW5b1h9Nrk1s
            q44MDwcSS4enloH3BVacxbQ4ZEtd39EwnrwyeSu0GWLK/XnwTucgSC5HGqQhU8fo
            knJFDYpzbXyYrKIZXJZVauBfpEE1C/i05qxKnhIXEGFNwpyVowK0Jfu49NgX3HG+
            SkURhymjPrtl4MOWZF29pjQOM8xZuD6xNGAcmPrC040/ddOHUetoVk/r
            -----END RSA PRIVATE KEY-----
          port: 22
          script: |
            cd /home/nojoomserver
            git clone https://github.com/walidmeguenni/cicd.git
            cd cicd
            git ckeckout main
            git pull origin main
            npm install
            npm run build
